/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.academiamas;

import java.awt.Dialog;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author a20alejandrofs
 */
public class JDAddAlumno extends javax.swing.JDialog {

    DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
    DefaultListModel<String> listModel = new DefaultListModel<>();
    List<Modulo> listaModulos = new ArrayList<>();
    VentanaPrincipal padre = (VentanaPrincipal) this.getParent();

    /**
     * Creates new form JDAddAlumno
     */
    public JDAddAlumno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNombreAlumno = new javax.swing.JTextField();
        textLocalidadAlumno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guardarAlumno = new javax.swing.JButton();
        limpiarAlumno = new javax.swing.JButton();
        comboModulos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaModulosAlumno = new javax.swing.JList<>();
        botonQuitarModulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Localidad: ");

        jLabel3.setText("Modulos:");

        jLabel4.setText("Añadir Alumno: ");

        guardarAlumno.setText("Guardar");
        guardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAlumnoActionPerformed(evt);
            }
        });

        limpiarAlumno.setText("Limpiar");
        limpiarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarAlumnoActionPerformed(evt);
            }
        });

        comboModulos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacio" }));
        comboModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModulosActionPerformed(evt);
            }
        });

        listaModulosAlumno.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Elige un modulo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaModulosAlumno);

        botonQuitarModulo.setText("Quitar");
        botonQuitarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardarAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(limpiarAlumno))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textLocalidadAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addComponent(textNombreAlumno)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonQuitarModulo)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(textNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textLocalidadAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonQuitarModulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarAlumno)
                    .addComponent(limpiarAlumno))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarAlumnoActionPerformed
        textNombreAlumno.setText("");
        textLocalidadAlumno.setText("");
        listaModulos.clear();
        listModel.clear();
        listaModulosAlumno.setModel(listModel);
    }//GEN-LAST:event_limpiarAlumnoActionPerformed

    private void comboModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModulosActionPerformed
        if (evt.getActionCommand().equals("comboBoxChanged")) {
            String nombreModulo = comboModulos.getSelectedItem().toString();
            listaModulos.add(padre.getFromModulosByNombre(nombreModulo));
            llenarListaModulos();
        }
    }//GEN-LAST:event_comboModulosActionPerformed

    private void guardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAlumnoActionPerformed
        Alumno alumno = new Alumno(textNombreAlumno.getText(), textLocalidadAlumno.getText(), listaModulos);
        if (comprobar(alumno)) {
            padre.addAlumnoLista(alumno);
            this.dispose();
        } else{
            JDialog errorDialog = new JDialog();
            errorDialog.setTitle("Error al guardar");
            errorDialog.setSize(300, 100);
            errorDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            errorDialog.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);

            JLabel errorMessage = new JLabel("Valores incorrectos");
            errorDialog.add(errorMessage);

            errorDialog.setLocationRelativeTo(null);
            errorDialog.setVisible(true);
        }
    }//GEN-LAST:event_guardarAlumnoActionPerformed

    private void botonQuitarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarModuloActionPerformed
        int index = listaModulosAlumno.getSelectedIndex();
        String nombreModulo = listModel.getElementAt(index);
        listModel.remove(index);
        listaModulos.remove(padre.getFromModulosByNombre(nombreModulo));
        llenarListaModulos();
    }//GEN-LAST:event_botonQuitarModuloActionPerformed

    private boolean comprobar(Alumno a) {
        int horas = 0;
        Iterator<Modulo> iter = listaModulos.iterator();
        while (iter.hasNext()) {
            Modulo modulo = iter.next();
            horas += modulo.getHoras();
        }
        if (a.getNombre() == "" || a.getLocalidad() == "" || horas > 30) {
            return false;
        }
        return true;
    }

    private void llenarListaModulos() {
        listModel.clear();
        Iterator<Modulo> iter = listaModulos.iterator();
        while (iter.hasNext()) {
            Modulo modulo = iter.next();
            listModel.addElement(modulo.getNombre());
        }
        listaModulosAlumno.setModel(listModel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAddAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAddAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAddAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAddAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAddAlumno dialog = new JDAddAlumno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void llenarCombo() {
        Iterator<Modulo> iter = padre.getListaModulos().iterator();
        while (iter.hasNext()) {
            Modulo modulo = iter.next();
            comboModel.addElement(modulo.getNombre());
        }
        comboModulos.setModel(comboModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonQuitarModulo;
    private javax.swing.JComboBox<String> comboModulos;
    private javax.swing.JButton guardarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarAlumno;
    private javax.swing.JList<String> listaModulosAlumno;
    private javax.swing.JTextField textLocalidadAlumno;
    private javax.swing.JTextField textNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
